export enum AppEntityIcons {
  AlbumArtist = 'mdi-account-badge mdi',
  Artist = 'mdi-account-music mdi',
  Album = 'mdi-album mdi',
  Song = 'mdi-music-note mdi',
  Classification = 'mdi-sitemap-outline mdi',
  Genre = 'mdi-tag mdi',
  Subgenre = 'mdi-tag-text mdi',
  Occasion = 'mdi-snowman mdi',
  Instrument = 'mdi-guitar-acoustic mdi',
  Category = 'mdi-sticker-text mdi',
  Playlist = 'mdi-playlist-play mdi',
  Smartlist = 'mdi-filter-variant mdi',
  Autolist = 'mdi-playlist-star mdi',
  Sync = 'mdi-sync mdi'
}

export enum AppFeatureIcons {
  MultipleArtists = 'mdi-account-multiple mdi',
  MultipleGenres = 'mdi-tag-multiple mdi',
  MultipleFilters = 'mdi-filter-multiple mdi',
  Statistics = 'mdi-chart-bar mdi',
  TagMapping = 'mdi-tag-arrow-right mdi',
  Mobile = 'mdi-cellphone mdi'
}

export enum AppAttributeIcons {
  ArtistName = 'mdi-account mdi',
  ArtistGroup = 'mdi-account-group mdi',
  ArtistStylized = 'mdi-symbol mdi',
  AlbumName = 'mdi-album mdi',
  SongName = 'mdi-music-clef-treble mdi',
  TitleSort = 'mdi-sort-alphabetical-variant mdi',
  SongCount = 'mdi-music mdi',
  GenreName = 'mdi-tag mdi',
  FileInfo = 'mdi-file-music mdi',
  ClassificationType = 'mdi-shape mdi',
  Language = 'mdi-translate mdi',
  MoodOn = 'mdi-emoticon mdi',
  MoodOff = 'mdi-emoticon-neutral-outline mdi',
  Year = 'mdi-calendar mdi',
  Decade = 'mdi-calendar-month mdi',
  RatingOn = 'mdi-star mdi',
  RatingOff = 'mdi-star-outline mdi',
  RatingHalf = 'mdi-star-half-full mdi',
  FavoriteOn = 'mdi-heart mdi',
  FavoriteOff = 'mdi-heart-outline mdi',
  LiveOn = 'mdi-access-point mdi',
  LiveOff = 'mdi-access-point-off mdi',
  LyricsOn = 'mdi-script-text-outline mdi',
  LyricsOff = 'mdi-script-outline mdi',
  Advisory = 'mdi-exclamation-thick mdi',
  ExplicitOn = 'mdi-alpha-e-box mdi',
  ExplicitOff = 'mdi-alpha-e-box-outline mdi',
  CleanOn = 'mdi-alpha-c-box mdi',
  CleanOff = 'mdi-alpha-c-box-outline mdi',
  Bitrate = 'mdi-wave mdi',
  Vbr = 'mdi-waveform mdi',
  Image = 'mdi-image mdi',
  ImageAnimated = 'mdi-video-image mdi',
  TrackNumber = 'mdi-pound mdi',
  MediaNumber = 'mdi-disc mdi',
  MediaSubtitle = 'mdi-disc mdi',
  Subtitle = 'mdi-subtitles mdi',
  Duration = 'mdi-timer mdi',
  PlayCount = 'mdi-counter mdi',
  AddDate = 'mdi-calendar-plus mdi',
  ChangeDate = 'mdi-calendar-edit mdi',
  AccessDate = 'mdi-calendar-cursor mdi',
  PlayDate = 'mdi-calendar-check mdi',
  ArtistType = 'mdi-account-tag mdi',
  AlbumType = 'mdi-export-variant mdi',
  Country = 'mdi-earth mdi',
  Gender = 'mdi-gender-male-female mdi',
  Directory = 'mdi-folder mdi',
  DirectoryInfo = 'mdi-folder-information mdi',
  DirectoryOpen = 'mdi-folder-open mdi',
  AudioDirectory = 'mdi-folder-music mdi',
  PlaylistDirectory = 'mdi-folder-play mdi',
  Description = 'mdi-note-text mdi',
  Grouping = 'mdi-format-list-group mdi',
  PerformerCount = 'mdi-account-group mdi',
  Limit = 'mdi-sort-numeric-variant mdi',
  LongPlay = 'mdi-clock-time-ten mdi',
  ShortPlay = 'mdi-clock-time-two mdi',
  Accent = 'mdi-vanish-quarter mdi',
  Contributor = 'mdi-account-supervisor mdi',
  SwitchOn = 'mdi-toggle-switch-variant mdi',
  SwitchOff = 'mdi-toggle-switch-variant-off mdi',
  Selected = 'mdi-checkbox-marked mdi',
  Unselected = 'mdi-checkbox-blank-outline mdi',
  Recent = 'mdi-history mdi',
  Checked = 'mdi-check-circle mdi',
  Bottom = 'mdi-arrow-collapse-down mdi',
  Top = 'mdi-arrow-collapse-up mdi',
  Vocal = 'mdi-account-voice mdi',
  Labels = 'mdi-label-multiple-outline mdi',
  Link = 'mdi-link mdi mdi-rotate-135',
  VideoOn = 'mdi-video mdi',
  VideoOff = 'mdi-video-off mdi',
  QualityLow = 'mdi-quality-low mdi',
  QualityMedium = 'mdi-quality-medium mdi',
  QualityHigh = 'mdi-quality-high mdi',
  Frequency = 'mdi-resistor mdi',
  ReplayGain = 'mdi-volume-equal mdi',
  BackgroundColor = 'mdi-alpha-b-box-outline mdi',
  PrimaryColor = 'mdi-numeric-1-box-outline mdi',
  SecondaryColor = 'mdi-numeric-2-box-outline mdi',
  Soundtrack = 'mdi-filmstrip mdi',
  Compilation = 'mdi-music-box-multiple mdi',
  Single = 'mdi-numeric-1-box mdi',
  Ep = 'mdi-numeric-1-box-multiple mdi',
  MbId = 'mdi-identifier mdi'
}

export enum AppActionIcons {
  Add = 'mdi-plus mdi',
  Edit = 'mdi-pencil mdi',
  Delete = 'mdi-delete mdi',
  Ok = 'mdi-check mdi',
  CloseClear = 'mdi-close mdi',
  Search = 'mdi-magnify mdi',
  SearchClose = 'mdi-magnify-remove-outline mdi',
  WebSearch = 'mdi-web mdi',
  Select = 'mdi-select mdi',
  Sort = 'mdi-sort-variant mdi',
  SortAscending = 'mdi-sort-ascending mdi',
  SortDescending = 'mdi-sort-descending mdi-flip-v mdi',
  Filter = 'mdi-filter-outline mdi',
  FilterClose = 'mdi-filter-remove-outline mdi',
  QuickFilter = 'mdi-filter-settings-outline mdi',
  Menu = 'mdi-menu mdi',
  DotsVertical = 'mdi-dots-vertical mdi',
  DotsHorizontal = 'mdi-dots-horizontal mdi',
  Scroll = 'mdi-arrow-up-down mdi',
  Back = 'mdi-arrow-left mdi',
  Up = 'mdi-arrow-up mdi',
  Down = 'mdi-arrow-down mdi',
  ExportData = 'mdi-database-export mdi',
  DeleteData = 'mdi-database-remove mdi',
  SearchData = 'mdi-database-search mdi',
  Debug = 'mdi-bug mdi',
  Code = 'mdi-file-code mdi',
  Test = 'mdi-test-tube mdi',
  AddToPlaylist = 'mdi-playlist-plus mdi',
  Loading = 'mdi-loading mdi-spin mdi',
  Alternate = 'mdi-shuffle-variant mdi',
  Scan = 'mdi-magnify-scan mdi',
  Share = 'mdi-share-variant mdi',
  Download = 'mdi-download mdi',
  Screenshot = 'mdi-cellphone-screenshot mdi',
  ResizeUp = 'mdi-resize mdi',
  ResizeDown = 'mdi-move-resize-variant',
  Import = 'mdi-import mdi-rotate-90 mdi',
  Export = 'mdi-export-variant mdi',
  ImportToDb = 'mdi-database-import mdi',
  ExportFromDb = 'mdi-database-export mdi',
  LevelUp = 'mdi-arrow-up-right-bold mdi',
  Config = 'mdi-tools mdi',
  Run = 'mdi-flash mdi',
  SmartlistRemove = 'mdi-filter-variant-remove mdi',
  PlaylistEdit = 'mdi-playlist-edit mdi',
  Drag = 'mdi-drag mdi',
  TimerAdd = 'mdi-timer-plus mdi',
  TimerRemove = 'mdi-timer-minus mdi',
  TimeBackward = 'mdi-replay mdi',
  TimeForward = 'mdi-replay mdi-flip-h mdi',
  PlusOne = 'mdi-numeric-positive-1 mdi',
  FileSync = 'mdi-file-sync mdi',
  Click = 'mdi-cursor-default-click-outline mdi',
  Aim = 'mdi-bullseye mdi',
  Undo = 'mdi-undo-variant mdi',
  ChevronLeft = 'mdi-chevron-left mdi',
  ChevronRight = 'mdi-chevron-right mdi'
}

export enum AppPlayerIcons {
  Play = 'mdi-play mdi',
  Pause = 'mdi-pause mdi',
  Stop = 'mdi-stop mdi',
  Previous = 'mdi-skip-previous mdi',
  Next = 'mdi-skip-next mdi',
  Rewind = 'mdi-rewind mdi',
  FastForward = 'mdi-fast-forward mdi',
  ShuffleOn = 'mdi-shuffle mdi',
  ShuffleOff = 'mdi-shuffle-disabled mdi',
  RepeatAll = 'mdi-repeat mdi',
  RepeatOff = 'mdi-repeat-off mdi',
  RepeatOne = 'mdi-repeat-once mdi',
  Queue = 'mdi-playlist-music-outline mdi',
  BackgroundColor = 'mdi-alpha-b-box-outline mdi',
  PrimaryColor = 'mdi-numeric-1-box-outline mdi',
  SecondaryColor = 'mdi-numeric-2-box-outline mdi',
  SelectedColor = 'mdi-cursor-default-click-outline mdi',
  CurrentColor = 'mdi-bullseye mdi',
  CollapsePlayer = 'mdi-chevron-down mdi'
}

export enum AppViewIcons {
  Home = 'mdi-home mdi',
  Settings = 'mdi-cogs mdi',
  Log = "mdi-file-document-edit mdi",
  About = 'mdi-owl mdi'
}

export function getNumericCircleIcon(value: number): string {
  if (value >= 0 && value < 10) {
    return `mdi-numeric-${value}-circle mdi`;
  }
  if (value > 9) {
    return 'mdi-numeric-9-plus-circle mdi';
  }
  return '';
}

export function getNumericBoxIcon(value: number): string {
  if (value >= 0 && value < 10) {
    return `mdi-numeric-${value}-box-outline mdi`;
  }
  if (value > 9) {
    return 'mdi-numeric-9-plus-box-outline mdi';
  }
  return '';
}
