export enum LocalStorageKeys {
    FacetCategories = 'sp.FacetCategories',
    Classifications = 'sp.Classifications',
    GroupedClassifications = 'sp.GroupedClassifications',
    RecentClassifications = 'sp.RecentClassifications',
    Session = 'sp.Session',
    DefaultRoute = 'sp.DefaultRoute',
    GenresAll = 'sp.GenresAll',
    GenresUsed = 'sp.GenresUsed',
    DecadesUsed = 'sp.DecadesUsed',
    RefineSearch = 'sp.RefineSearch',
    Settings = 'sp.Settings',
    RestCache = 'sp.RestCache',
    ArtistTypes = 'sp.ArtistTypes',
    Countries = 'sp.Countries',
    ModalSelectionItems = 'sp.ModalSelectionItems',
    SpotifyToken = 'sp.SpotifyToken',
    Filters = 'sp.Filters',
    ValueListEntries = 'sp.ValueListEntries',
    ColorUtility = 'sp.ColorUtility',
    RelatedImages = 'sp.RelatedImages'
}